# Paths
set(PROTO_DIR ${CMAKE_CURRENT_SOURCE_DIR}/proto)
set(NANOPB_GEN_DIR ${CMAKE_CURRENT_BINARY_DIR}/generated/nanopb)
set(PY_PROTO_GEN_DIR ${CMAKE_CURRENT_BINARY_DIR}/generated/python)

# Make the directories in the build folder (to keep it clean)
file(MAKE_DIRECTORY ${NANOPB_GEN_DIR})
file(MAKE_DIRECTORY ${PY_PROTO_GEN_DIR})

# Find .proto files
file(GLOB PROTO_FILES ${PROTO_DIR}/*.proto)

# Determine the correct plugin extension depending on the OS
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
  set(NANOPB_PLUGIN_EXT ".bat")
else()
  set(NANOPB_PLUGIN_EXT "")
endif()

# NanoPB (generates pb.c, pb.h)
foreach(PROTO_FILE ${PROTO_FILES})
  # Get the .proto file without extension
  get_filename_component(PROTO_NAME ${PROTO_FILE} NAME_WE)

  # For cpp (nanopb)
  add_custom_command(
    OUTPUT
      ${NANOPB_GEN_DIR}/${PROTO_NAME}.pb.c
      ${NANOPB_GEN_DIR}/${PROTO_NAME}.pb.h
    COMMAND protoc
      --proto_path=${PROTO_DIR}
      --plugin=protoc-gen-nanopb=${CMAKE_CURRENT_SOURCE_DIR}/nanopb/generator/protoc-gen-nanopb${NANOPB_PLUGIN_EXT}
      --nanopb_out=${NANOPB_GEN_DIR}
      ${PROTO_FILE}
    DEPENDS ${PROTO_FILE}
    COMMENT "Running nanopb generator on ${PROTO_NAME}.proto"
    VERBATIM
  )
  list(APPEND NANOPB_SRCS ${NANOPB_GEN_DIR}/${PROTO_NAME}.pb.c)
  list(APPEND NANOPB_HDRS ${NANOPB_GEN_DIR}/${PROTO_NAME}.pb.h)

  # For python (protobuf)
  add_custom_command(
    OUTPUT
      ${PY_PROTO_GEN_DIR}/${PROTO_NAME}_pb2.py
    COMMAND protoc
      --proto_path=${PROTO_DIR}
      --python_out=${PY_PROTO_GEN_DIR}
      ${PROTO_FILE}
    DEPENDS ${PROTO_FILE}
    COMMENT "Running python protobuf generator on ${PROTO_NAME}.proto"
    VERBATIM
  )
  list(APPEND PY_PROTO_SRCS ${PY_PROTO_GEN_DIR}/${PROTO_NAME}_pb2.py)

endforeach()

add_custom_target(proto_gen ALL
  DEPENDS
  ${NANOPB_SRCS}
  ${PY_PROTO_SRCS}
)

set(NANOPB_IMPLEMENTATION 
  ${CMAKE_CURRENT_SOURCE_DIR}/nanopb/pb_encode.c 
  ${CMAKE_CURRENT_SOURCE_DIR}/nanopb/pb_decode.c 
  ${CMAKE_CURRENT_SOURCE_DIR}/nanopb/pb_common.c)

# FYI: 
# NANOPB_GEN_DIR = NANOPB_SRCS + NANOPB_HDRS
# NANOPB_SRCS - Source files (.c) generated by nanopb for your protobuf messages (.pb.h)
# NANOPB_HDRS - Header files (.h) generated by nanopb for your protobuf messages (.pb.c)
# NANOPB_IMPLEMENTATION - Core implementation files of the nanopb library (pb_encode.c, pb_decode.c, pb_common.c)

# *** Our conversion library ***

# Recursively search for header and source files in the include and src directories
file(GLOB_RECURSE HEADERS "include/*.h")
file(GLOB_RECURSE SOURCES "src/*.cpp")

# Create a library named ctrl_lib using the headers and sources found
add_library(msg_lib ${HEADERS} ${SOURCES}   
  ${NANOPB_SRCS} ${NANOPB_HDRS} ${NANOPB_IMPLEMENTATION}
)

# Specify the include directory for the ctrl_lib target
target_include_directories(msg_lib PUBLIC include)
target_link_libraries(msg_lib PRIVATE debug_lib cfg_lib)
# find the pb.h files
target_include_directories(msg_lib PUBLIC 
  ${NANOPB_GEN_DIR} # the pb.h file
  ${CMAKE_CURRENT_SOURCE_DIR}/nanopb # decode.c, encode.c...
)

if (BUILD_ON_STM)
  target_compile_options(msg_lib PRIVATE -Os)
  target_compile_options(msg_lib PRIVATE -ffunction-sections)
  target_compile_options(msg_lib PRIVATE -fdata-sections)
  target_link_options(msg_lib PRIVATE -Wl,--gc-sections)
else()
  add_subdirectory(demo)
endif()