#ifndef MESSAGE_INTERFACE_H
#define MESSAGE_INTERFACE_H

#include <stdint.h>

#include <string_view>
#include <vector>

// This header will be generated by nanopb generator (using the message.proto) through cmake
#include "message.pb.h"
#include "pb_decode.h"
#include "pb_encode.h"

struct StringPayload {
  const uint8_t* data;
  size_t size;
};

struct StringPayloadDecode {
  uint8_t* buffer;
  size_t buffer_size;
  size_t* bytes_written;
};

bool PayloadEncodeCallback(pb_ostream_t* stream, const pb_field_t* field, void* const* arg);
bool PayloadDecodeCallback(pb_istream_t* stream, void** arg);

#endif  // MESSAGE_INTERFACE_H
